### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by teorzhang** [Hannibal046/SDDS#1]
请问，提供的samsum_train.json里的discourse_relations和keywords是需要自己构造吗？我运行会出现这个问题（UnboundLocalError: local variable 'discourse_relations_per_instance' referenced before assignment），在读取samsum_train.json里的数据时discourse_relations和keywords为None。

**Comment by Hannibal046** [comment]
哈喽,
数据已经更新了!

**Comment by teorzhang** [comment]
感谢回复。

**Comment by teorzhang** [comment]
请问可以多卡训练吗？我设置了CUDA_VISIBLE_DEVICES=0,1，会报这两个错误：untimeError: Caught RuntimeError in replica 0 on device 0.    
low_encoder_output_batched = low_encoder_output_batched.view(bs,max_utt_num_in_a_batch,d_model)
RuntimeError: shape '[1, 24, 1024]' is invalid for input of size 49152
