### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by teorzhang** [Hannibal046/SDDS#2]
请问代码中low_encoder和high_encoder中的low和high代表什么意思呢？

**Comment by Hannibal046** [comment]
low: low-level feature(token)
high: high-level feature(utterance)

**Comment by teorzhang** [comment]
明白了，感谢回复。另外想问一下，Static-Dynamic Fusion Module是在GraphTransformerMultiHeadAttentionLayer中体现吗？

**Comment by Hannibal046** [comment]
Hi, 具体的代码实现可以参考:
https://github.com/Hannibal046/SDDS/blob/8ba2a10f670359ffcf8d0eb85a85b921afa9e888/src/model/graphtransformer.py#L194-L197

**Comment by teorzhang** [comment]
明白了，感谢

**Comment by teorzhang** [comment]
请问大佬，实验中对比的BART基准数据是用哪个代码跑的呢？我想学习一下BART模型源码，哪里能学习到呢？（transformer官方的代码很多地方没详解，有点看不懂。。）

**Comment by Hannibal046** [comment]
BART的源代码我也是用的Huggingface的版本: https://github.com/huggingface/transformers/blob/main/src/transformers/models/bart/modeling_bart.py
Baseline代码可以参考:
https://github.com/huggingface/transformers/tree/main/examples/pytorch/summarization

**Comment by teorzhang** [comment]
好的 感谢
