### ISSUE TITLE
Correct batch size to reproduce results

### ISSUE THREAD

**Issue by wdhorton** [Hannibal046/SDDS#3]
The paper mentions that training was done with batch size of 16, but the config in the repo uses `per_device_train_batch_size` of 1. https://github.com/Hannibal046/SDDS/blob/main/src/config/graphbart_config.json#L51

Which is the right setting to try to reproduce the results on the SamSum dataset?

**Comment by Hannibal046** [comment]
Hi, thanks for the interest in our work. The batch size in the paper refer to the `effective batch size` which is the product of `per_device_train_batch_size` and `gradient_accumulation_steps`. In the config file, it is `1*8`, which should be the one we use (if i remember correctly). Sorry for the confusion and feel free to ask if there is any further problem.
