### ISSUE TITLE
About DialogSum dataset

### ISSUE THREAD

**Issue by ling8** [Hannibal046/SDDS#5]
Can you provide me with the processed Dialogsum dataset,  I can't configure the environment in https://github.com/shizhouxing/DialogueDiscourseParsing

**Comment by Hannibal046** [comment]
Hi, I don't I think I kept that data. You can use the command provided in this repo to get the discourse parsing results. It takes a while to configure the environment because it uses tensorflow 1.0. We set up that environment on a 1080Ti GPU

**Comment by ling8** [comment]
ok ,thank you
