### ISSUE TITLE
evaluate on dialogsum

### ISSUE THREAD

**Issue by ling8** [Hannibal046/SDDS#6]
Please, I would like to know if the results presented on the paper are the average results of the summary1,2,3 of the dialogsum_test when evaluated on the dialogsum dataset

**Comment by Hannibal046** [comment]
Yes, we use multiple reference:
![image](https://github.com/Hannibal046/SDDS/assets/38466901/1a192d6f-9d83-4341-8f0f-1f8ba30c490c)

**Comment by ling8** [comment]
Sorry, I see
